name = "shop-bot-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "shop-db"
database_id = "35d0b35a-ae48-425c-ac56-29e87d2d6470"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "shop-uploads"

[vars]
SERVER_URL = "https://telegram-shop-bot.pages.dev"
